### ISSUE TITLE
trailing space mandatory ?

### ISSUE THREAD

**Issue by paulgirard** [Yomguithereal/phonogram#18]
without trailing space
![image](https://user-images.githubusercontent.com/193478/35982528-576ac41a-0cf0-11e8-96ce-ad3ca034f51a.png)
with trailing space
![image](https://user-images.githubusercontent.com/193478/35982549-651cee4e-0cf0-11e8-9ac4-3bb0aeb508d9.png)

**Comment by Yomguithereal** [comment]
Fixed :)
